name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: yarn install && yarn build
        env:
          CI: true

      - name: Archive
        run: cd dist/ && zip -r ../build.zip *

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr
          path: dist/
          remote_path: /srv/www/boluo.chat/frontend/
          remote_host: boluo.chat
          remote_user: boluo-frontend
          remote_key: ${{ secrets.BOLUO_DEPLOY }}
