name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: yarn install && yarn build
        env:
          CI: true

      - name: Archive
        run: cd dist/ && zip -r ../build.zip *

      - name: Upload to B2
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync ./dist/ b2:boluo-backup/dist/

      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /srv/www/boluo.chat/frontend/
          remote_host: boluo.chat
          remote_user: boluo-frontend
          remote_key: ${{ secrets.BOLUO_DEPLOY }}
