name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: build
        run: yarn install && yarn build
        env:
          CI: true
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /var/www/boluo/frontend/
          remote_host: 34.96.214.244
          remote_user: boluo-frontend
          remote_key: ${{ secrets.BOLUO_DEPLOY }}
