name: Release
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: build
        run: yarn install && yarn build
        env:
          CI: true

      - name: Package
        run: zip -r boluo.zip dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: boluo-web
          path: dist/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: boluo.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
